server:
  port: 8103

verification-code-receiver:
  port: 8188

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:8432/why?currentSchema=schedules
    username: why_schedules_usr
    password: b?Wuy9XLB$
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  liquibase:
    default-schema: schedules
    enabled: true

calendar:
  settings:
    app-name: Why Studio
    tokens-dir: tokens
    creds-path: /google-calendar-credentials.json
  id: why-studio.com_1884je5jtgudojlbmpmso91p9n7a86gb68r32d1i6gpj2dhl6k@resource.calendar.google.com

services:
  auth:
    url: http://localhost:8102/
    user-info: ${services.auth.url}user/